[package]
name = "beacon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
lab = "*"
deltae = "*"
crossbeam = "0.8"
ndarray = "*"
indicatif = "0.17.8"
fastrand = "2.1.0"
